### ISSUE TITLE
ScrolledFrame doesn’t seem to work as aspected

### ISSUE THREAD

**Issue by Funpy97** [israel-dryer/ttkbootstrap#169] opened 2022-02-01 02:56 UTC
To test the ScrolledFrame widget i've wrote the follow code:
```
from ttkbootstrap import *
from ttkbootstrap.scrolled import ScrolledFrame


class MainView(Window):
    def __init__(self):
        super(MainView, self).__init__()

        sf = ScrolledFrame(self)
        for i in range(20):
            Label(sf, text=f"Label {i}").pack()
        sf.pack(fill=BOTH, expand=True)


if __name__ == "__main__":
    app = MainView()
    app.mainloop()
```
and this was the output:
![sf_error](https://user-images.githubusercontent.com/73608319/151905842-94722d76-bcb8-4211-9581-0375284206f3.JPG)
as you can see the Scrollbar wasn't showing the right proportion.

I used
- ttkbootstrap 1.5.1
- Python 3.8.3
- Windows 10

**Comment by israel-dryer** [comment] 2022-02-01 21:15
I'll have to think about this one. It's easy to make sure the initial settings are correct. But, when the container is expanded or contracted, this is when setting the behavior becomes a bit more complicated. I want to make sure I don't break one thing by fixing another. Thanks for raising the issue.

**Comment by lolghuiy4tgfyu4th7tvtg** [comment] 2022-02-01 22:00
Hey, I got the same problem too ...

![sC9YNRjIOD](https://user-images.githubusercontent.com/78936316/152058596-12c5c47e-ac6b-4140-b494-f55b13e974bf.gif)

**Comment by israel-dryer** [comment] 2022-02-02 04:24
> Hey, I got the same problem too ... but only in ttkbootstrap 1.5.1
> 
> ![sC9YNRjIOD](https://user-images.githubusercontent.com/78936316/152058596-12c5c47e-ac6b-4140-b494-f55b13e974bf.gif)

I think what broke this was a fix for another issue https://github.com/israel-dryer/ttkbootstrap/commit/aeb0b990d45f757d3c4e07cf45102b46d4addccc

Unfortunately, the behavior of this widget is a lot more complicated that I had hoped, so I'm going to have to think about the expected behavior in various situations, especially as it relates to allowing the canvas to shrink and grow and how this affects the underlying frame. I hope to have a fix for this soon.

**Comment by israel-dryer** [comment] 2022-02-02 21:33
@Funpy97, @lolghuiy4tgfyu4th7tvtg I think this should fix your issue. Try installing the branch below. If this solves your problem, I'll merge this with the main branch.
```
pip install git+https://github.com/israel-dryer/ttkbootstrap.git@fix-scrolledframe-behavior
```

There is one caveat that may not affect you, but I'll mention it anyway. If you add widgets to the scrolled frame _after_ the window is already drawn, then you will need to call the `ScrolledFrame.refresh_geometry()` method to force the container scrollbar to account for the new widgets.

**Comment by israel-dryer** [comment] 2022-02-03 00:11
I'm going to go ahead and merge this branch. However, I'll keep the issue open if  turns out there are still some quirks with various use-cases.

**Comment by Funpy97** [comment] 2022-02-03 01:14
@israel-dryer I updated and tested the same code and now it works.
You are doing a great job around tkinter!

**Comment by israel-dryer** [comment] 2022-02-03 01:18
>  @israel-dryer I updated and tested the same code and now it works.
> You are doing a great job around tkinter!

Glad to hear. Thanks for sending the update.

**Comment by lolghuiy4tgfyu4th7tvtg** [comment] 2022-02-03 17:11
It seems to work, with the refresh_geometry and all, but every time I change what's in the frame, I have to resize the window for it to work.

![ArvYTVh87y](https://user-images.githubusercontent.com/78936316/152393300-b486f5c3-af31-44a4-ba4b-0ee31dbb874d.gif)

**Comment by israel-dryer** [comment] 2022-02-04 23:36
@lolghuiy4tgfyu4th7tvtg, I'm not very happy with the Scrolledframe yet. I worked out some code from examples across the internet in the current version. However, I've been working on a completely new model using just 2 frames and a scrollbar without any canvas, etc... It requires me to build my own yview and scrollcommand functions, but it seems to be performing much better. I'm hopefully that this will work better instead of a convoluted canvas creation. However, I still need to finish building it out and testing it. I'm hopeful. Below is a sample of what I'm working on.. it's model in vanilla tkinter using the clam theme, so it's not in ttkbootstrap yet.

![Code_xAlQNMBawh](https://user-images.githubusercontent.com/42584742/152617083-a3181673-e611-4381-a97f-4169b24719ff.gif)

**Comment by israel-dryer** [comment] 2022-02-08 01:41
I've refactor the ScrolledFrame widget and I believe it works much better. However, let me know the results on your end. You can read the pull request notes above for details.

**Comment by israel-dryer** [comment] 2022-02-08 17:13
> It seems to work better, but one thing I noticed (and this might just be with my program) is that when the frame is expanded like this, the autohide just hides behind the frame contents, instead of disappearing, but besides that, this fix fixes everything. Thanks!
> 
> ![dwG2sNfXGG](https://user-images.githubusercontent.com/78936316/153027677-671070e5-017d-4f7c-bb45-1a17ba9a9e76.gif)
> 
> 

Ah. Good catch. I thought I could get away with the the lift and lower, but looks like I'll need to actually unpack the scrollbar. I'll make sure this is fixed in the next release.

**Comment by israel-dryer** [comment] 2022-02-08 18:39
@lolghuiy4tgfyu4th7tvtg I pushed the fix in version 1.7.1

**Comment by lolghuiy4tgfyu4th7tvtg** [comment] 2022-02-08 18:47
wow, that was fast.

**Comment by lolghuiy4tgfyu4th7tvtg** [comment] 2022-02-08 18:49
Well, it works now.
Thanks for fixing it!

**Closed** 2022-02-09 00:34 UTC
Labels: bug
