### ISSUE TITLE
Error opening font dialog in Linux Mint

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#154] opened 2022-01-23 22:48 UTC
OS: Linux Mint x64 Cinnamon 20.3 X11
ttkbootstrap: github master version

When trying to run this code below, this message appears:

> .....ttkbootstrap/dialogs/dialogs.py", line 966, in _font_families_selector
>     listbox.insert("", iid=f, index=END, tags=[f], values=[f])
>   File "/usr/lib/python3.8/tkinter/ttk.py", line 1361, in insert
>     res = self.tk.call(self._w, "insert", parent, index,
> _tkinter.TclError: Item Roboto Condensed already exists

--------------

```
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.dialogs import colorchooser
from ttkbootstrap.dialogs import FontDialog

def test():
    #cd = colorchooser.ColorChooserDialog()
    #cd.show()

    fd = FontDialog()
    fd.show()

app = ttk.Window(size=(300,300))

frm = ttk.Frame(app)
frm.pack(fill=BOTH, expand=YES, padx=10, pady=10)

btn0 = ttk.Button(frm, text='clickme', command=test)
btn0.pack()

app.mainloop() 
```

**Comment by israel-dryer** [comment] 2022-01-24 00:15
Let me know if this fixes the issue. If so, you can go ahead and close the issue.
I don't like how the dialog is sized currently, but I had to make some adjustments so that the preview was visible in Mac, Linux and Windows. I'll try to update this logic in the future.

**Comment by antrrax** [comment] 2022-01-24 00:47
Yes now opened the font dialog.
However, a flashing animation appears on the screen, it seems that the window is built in white and with a small size, then it gets bigger, this behavior is expected, see the video:
https://www.mediafire.com/file/ux3gmz74zhw59sa/fontdialog.mp4/file

here is a screenshot of the video frame

<img src="https://i.ibb.co/5sRM7tV/error.png" alt="error" border="0">

**Comment by israel-dryer** [comment] 2022-01-24 01:54
Ok. I know the issue you're talking about. I'll see if there is something that can be done. Windows, Linux, and Mac all handle the window events different, and this is one of those that has been a constant thorn.

**Comment by israel-dryer** [comment] 2022-01-24 02:28
If you're ever interested in playing around with it, Linux Mint (Ubuntu specifically) does not behave normally with the `iconify` command.

```python
# import tkinter as tk

# root = tk.Tk()
# root.title('root')
# top = tk.Toplevel()
# top.title('top')

# tk.Button(root, text='Show', command=top.deiconify).pack()
# tk.Button(root, text='iconify', command=top.iconify).pack()
# tk.Button(root, text='withdraw', command=top.withdraw).pack()

# root.mainloop()
```

If you withdraw the screen, you can use the iconify to show it again. However, once a window has been iconified, the deiconify command appears to have no effect.

The problem is that certain things cannot be done when the window is withdrawn. So, it is a balance between hiding the window to build it out and then show it completed, and being able to actually update it.

**Comment by israel-dryer** [comment] 2022-01-24 02:37
Ok. I think I found a potential fix.... 

1. Iconify the Toplevel widget when it's first created.
2. Withdraw the Toplevel after building it out to reset the iconified state
3. Deiconify the Toplevel and show it fully built on the screen.

This seems to show a smooth transition to a fully built dialog.

**Comment by antrrax** [comment] 2022-01-24 04:58
I tested it here, this new fix solved the problem

Very good

**Closed** 2022-01-24 05:15 UTC
